imports:
  - { resource: Backend/Widgets/ListOfMembersWidget.yaml }
  - { resource: Backend/Widgets/ListOfLastModifiedPagesWidget.yaml }
  - { resource: Backend/Widgets/ListOfLastCreatedPagesWidget.yaml }
  - { resource: Backend/Widgets/ListOfWorkspacePreviewLinksWidget.yaml }