imports:
  - { resource: Backend/Widgets/ListOfMembersWidget.yaml }
  - { resource: Backend/Widgets/LastModifiedPagesWidget.yaml }
  - { resource: Backend/Widgets/LastCreatedPagesWidget.yaml }
  - { resource: Backend/Widgets/WorkspacePreviewsWidget.yaml }
  - { resource: Backend/Widgets/PagesWithoutModificationWidget.yaml }
  - { resource: Backend/Widgets/RecentlyModifiedContentWidget.yaml }
  - { resource: Backend/Widgets/NumberOfRecordsByContentWidget.yaml }
